### ISSUE TITLE
Typo in the title

### ISSUE THREAD

**Issue by junegunn** [ikhoon/daum-mail-checker#1]
Please chekc it out.

**Comment by junegunn** [comment]
![빨리 고쳐주세요 현기증 난단 말이에요](http://cfile5.uf.tistory.com/image/166FA41949CDA8013721D9)

Any progress on this?

**Comment by ikhoon** [comment]
ㅋㅋㅋㅋㅋ 여기와서 이러지 마라

**Comment by ikhoon** [comment]
fixed!
